# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test My Project

on:
   workflow_dispatch:
  push:
  pull_request:
    types: [opened, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: installation
        run: npm install --save-dev cypress-cucumber-preprocessor

      - name: installation2
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm test

