name: FittedUI-AutomatedTest
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: installation
        run: npm install --save-dev cypress-cucumber-preprocessor
        
      - name: installation2
        run: npm install
        
      - name: run pretest
        run: npm run pretest
        
      - name: html test results into one
        uses: cypress-io/github-action@v2
        with:
          start: npm html:report

      - name: Deploy report page
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: mochareports.html
          
