name: FittedUI-AutomatedTest
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: installation
        run: npm install --save-dev cypress-cucumber-preprocessor
        
      - name: installation2
        run: npm install
        
      - name: run pretest
        run: npm run pretest
        
      - name: html test results into one
        run: npm run html:report

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          
